export const NotificationTypes = {
  ASSET_ASSIGNED: 'ASSET_ASSIGNED',
  ASSET_RETURNED: 'ASSET_RETURNED',
  TRANSFER_REQUEST: 'TRANSFER_REQUEST',
  TRANSFER_APPROVED: 'TRANSFER_APPROVED',
  TRANSFER_REJECTED: 'TRANSFER_REJECTED',
  BOOKING_CREATED: 'BOOKING_CREATED',
  BOOKING_CANCELLED: 'BOOKING_CANCELLED',
  BOOKING_REMINDER: 'BOOKING_REMINDER',
  MAINTENANCE_CREATED: 'MAINTENANCE_CREATED',
  MAINTENANCE_APPROVED: 'MAINTENANCE_APPROVED',
  MAINTENANCE_REJECTED: 'MAINTENANCE_REJECTED',
  MAINTENANCE_RESOLVED: 'MAINTENANCE_RESOLVED',
  AUDIT_ASSIGNED: 'AUDIT_ASSIGNED',
  AUDIT_COMPLETED: 'AUDIT_COMPLETED',
  OVERDUE_RETURN: 'OVERDUE_RETURN',
  SYSTEM: 'SYSTEM',
};

export const LogActions = {
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  CREATE: 'CREATE',
  UPDATE: 'UPDATE',
  DELETE: 'DELETE',
  ALLOCATE: 'ALLOCATE',
  RETURN: 'RETURN',
  TRANSFER: 'TRANSFER',
  APPROVE: 'APPROVE',
  REJECT: 'REJECT',
  BOOK: 'BOOK',
  CANCEL: 'CANCEL',
  AUDIT: 'AUDIT',
  EXPORT: 'EXPORT',
};

export default {
  NotificationTypes,
  LogActions,
};
// Map constants to top level src folder for compatibility
